const config = {
	NODE_ENV: process.env.NODE_ENV,
	DATABASE_PROD: process.env.DATABASE_PROD,
	DATABASE_PASS: process.env.DATABASE_PASS,
	DATABASE_LOCAL: process.env.DATABASE_LOCAL,
	PORT: process.env.PORT,
	JWT_SECRET: process.env.JWT_SECRET,
	JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
	JWT_COOKIES_EXPIRES_IN: process.env.JWT_COOKIES_EXPIRES_IN,
	CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
	CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
	CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
	MAILGUN_API_KEY: process.env.MAILGUN_API_KEY,
	MAILGUN_DOMAIN: process.env.MAILGUN_DOMAIN,
	EMAIL_FROM: process.env.EMAIL_FROM,
	EMAIL_PASS: process.env.EMAIL_PASS,
};

module.exports = config;
